# Custom Language File for Launcher Customizer

[ejs.app]
title = "Horizon Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/Ylizioops/HorizonLauncher"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.com/channels/1366100936207892540/1366317650178736178"

[ejs.settings]
sourceGithubLink = "https://github.com/Ylizioops/HorizonLauncher"
supportLink = "https://github.com/Ylizioops/HorizonLauncher/issues"

[ejs.welcome]
welcomeHeader = "BIENVENUE SUR HORIZON"
welcomeDescription = "L'ESPACE."
welcomeDescCTA = "Apprêtez vous à une aventure de folie !"
