[ejs.landing]
updateAvailableTooltip = "Mise à jour disponible"
usernamePlaceholder = "Nom d'utilisateur"
usernameEditButton = "Modifier"
settingsTooltip = "Paramètres"
serverStatus = "SERVEUR"
serverStatusPlaceholder = "HORS LIGNE"
mojangStatus = "STATUT MOJANG"
mojangStatusTooltipTitle = "Services"
mojangStatusNETitle = "Non&nbsp;Essentiel"
newsButton = "NOUVELLES"
launchButton = "JOUER"
launchButtonPlaceholder = "&#8226; Aucun serveur sélectionné"
launchDetails = "Veuillez patienter..."
newsNavigationStatus = "{currentPage} sur {totalPages}"
newsErrorLoadSpan = "Vérification des nouvelles..."
newsErrorFailedSpan = "Échec du chargement des nouvelles"
newsErrorRetryButton = "Réessayer"
newsErrorNoneSpan = "Aucune nouvelle"

[ejs.login]
loginCancelText = "Annuler"
loginSubheader = "CONNEXION MINECRAFT"
loginEmailError = "* Valeur invalide"
loginEmailPlaceholder = "E-MAIL OU NOM D'UTILISATEUR"
loginPasswordError = "* Requis"
loginPasswordPlaceholder = "MOT DE PASSE"
loginForgotPasswordLink = "https://minecraft.net/password/forgot/"
loginForgotPasswordText = "mot de passe oublié ?"
loginRememberMeText = "se souvenir de moi ?"
loginButtonText = "CONNEXION"
loginNeedAccountLink = "https://minecraft.net/store/minecraft-java-edition/"
loginNeedAccountText = "Besoin d'un compte ?"
loginPasswordDisclaimer1 = "Votre mot de passe est envoyé directement à Mojang et n'est jamais stocké."
loginPasswordDisclaimer2 = "{appName} n'est pas affilié à Mojang AB."

[ejs.loginOptions]
loginOptionsTitle = "Options de connexion"
loginWithMicrosoft = "Connexion avec Microsoft"
loginWithMojang = "Connexion avec Mojang"
cancelButton = "Annuler"

[ejs.overlay]
serverSelectHeader = "Serveurs Disponibles"
serverSelectConfirm = "Sélectionner"
serverSelectCancel = "Annuler"
accountSelectHeader = "Sélectionner un compte"
accountSelectConfirm = "Sélectionner"
accountSelectCancel = "Annuler"

[ejs.settings]
navHeaderText = "Paramètres"
navAccount = "Compte"
navMinecraft = "Minecraft"
navMods = "Mods"
navJava = "Java"
navLauncher = "Launcher"
navAbout = "À propos"
navUpdates = "Mises à jour"
navDone = "Terminé"
tabAccountHeaderText = "Paramètres du compte"
tabAccountHeaderDesc = "Ajoutez de nouveaux comptes ou gérez les comptes existants."
microsoftAccount = "Microsoft"
addMicrosoftAccount = "+ Ajouter un compte Microsoft"
mojangAccount = "Mojang"
addMojangAccount = "+ Ajouter un compte Mojang"
minecraftTabHeaderText = "Paramètres Minecraft"
minecraftTabHeaderDesc = "Options liées au lancement du jeu."
gameResolutionTitle = "Résolution du jeu"
launchFullscreenTitle = "Lancer en plein écran."
autoConnectTitle = "Se connecter automatiquement au serveur au lancement."
launchDetachedTitle = "Lancer le processus du jeu séparément du launcher."
launchDetachedDesc = "Si le jeu n'est pas détaché, fermer le launcher fermera également le jeu."
tabModsHeaderText = "Paramètres des Mods"
tabModsHeaderDesc = "Activer ou désactiver des mods."
switchServerButton = "Changer"
requiredMods = "Mods Requis"
optionalMods = "Mods Optionnels"
dropinMods = "Mods Drop-in"
addMods = "Ajouter des Mods"
dropinRefreshNote = "(F5 pour actualiser)"
shaderpacks = "Shaders"
shaderpackDesc = "Activer ou désactiver les shaders. Veuillez noter que les shaders ne fonctionnent correctement que sur des configurations puissantes. Vous pouvez ajouter vos propres packs ici."
selectShaderpack = "Sélectionner un Shader"
tabJavaHeaderText = "Paramètres Java"
tabJavaHeaderDesc = "Gérer la configuration Java (avancé)."
memoryTitle = "Mémoire"
maxRAM = "RAM Maximum"
minRAM = "RAM Minimum"
memoryDesc = "Le minimum recommandé est de 3 gigaoctets. Régler le minimum et le maximum sur la même valeur peut réduire les saccades."
memoryTotalTitle = "Total"
memoryAvailableTitle = "Disponible"
javaExecutableTitle = "Exécutable Java"
javaExecSelDialogTitle = "Sélectionner l'exécutable Java"
javaExecSelButtonText = "Choisir un fichier"
javaExecDesc = "L'exécutable Java est validé avant le lancement du jeu."
javaPathDesc = "Le chemin doit se terminer par <strong>{pathSuffix}</strong>."
jvmOptsTitle = "Options JVM additionnelles"
jvmOptsDesc = "Options à fournir à la JVM au démarrage. <em>-Xms</em> et <em>-Xmx</em> ne doivent pas être inclus."
launcherTabHeaderText = "Paramètres du Launcher"
launcherTabHeaderDesc = "Options liées au launcher lui-même."
allowPrereleaseTitle = "Autoriser les mises à jour Pré-Release."
allowPrereleaseDesc = "Les Pré-Releases incluent de nouvelles fonctionnalités qui n'ont peut-être pas été totalement testées.<br>Ceci sera toujours activé si vous utilisez déjà une version pré-release."
dataDirectoryTitle = "Répertoire de données"
selectDataDirectory = "Sélectionner le répertoire de données"
chooseFolder = "Choisir un dossier"
dataDirectoryDesc = "Tous les fichiers de jeu et les installations Java locales seront stockés ici.<br>Les captures d'écran et les mondes sont stockés dans le dossier d'instance correspondant au serveur."
aboutTabHeaderText = "À propos"
aboutTabHeaderDesc = "Voir les informations et les notes de version de la version actuelle."
aboutTitle = "{appName}"
stableRelease = "Version Stable"
versionText = "Version "
sourceGithub = "Source (GitHub)"
support = "Support"
devToolsConsole = "Console DevTools"
releaseNotes = "Notes de version"
changelog = "Changelog"
noReleaseNotes = "Aucune note de version"
viewReleaseNotes = "Voir les notes sur GitHub"
launcherUpdatesHeaderText = "Mises à jour du Launcher"
launcherUpdatesHeaderDesc = "Télécharger, installer et consulter les mises à jour du launcher."
checkForUpdates = "Vérifier les mises à jour"
whatsNew = "Quoi de neuf ?"
updateReleaseNotes = "Notes de mise à jour"

[ejs.waiting]
waitingText = "Attente de Microsoft..."

[ejs.welcome]
continueButton = "CONTINUER"


[js.discord]
waiting = "En attente du client..."
state = "Serveur : {shortId}"

[js.index]
microsoftLoginTitle = "Connexion Microsoft"
microsoftLogoutTitle = "Déconnexion Microsoft"

[js.login]
login = "CONNEXION"
loggingIn = "CONNEXION EN COURS"
success = "SUCCÈS"
tryAgain = "Réessayer"

[js.login.error]
invalidValue = "* Valeur invalide"
requiredValue = "* Requis"

[js.login.error.unknown]
title = "Erreur inconnue lors de la connexion"
desc = "Une erreur inconnue est survenue. Veuillez consulter la console pour plus de détails."

[js.landing.launch]
pleaseWait = "Veuillez patienter..."
failureTitle = "Erreur lors du lancement"
failureText = "Consultez la console (CTRL + Shift + i) pour plus de détails."
okay = "OK"

[js.landing.selectedAccount]
noAccountSelected = "Aucun compte sélectionné"

[js.landing.selectedServer]
noSelection = "Aucun serveur sélectionné"
loading = "Chargement..."

[js.landing.serverStatus]
server = "SERVEUR"
offline = "OFFLINE"
players = "JOUEURS"

[js.landing.systemScan]
checking = "Vérification des infos système..."
noCompatibleJava = "Aucune installation Java<br>compatible trouvée"
installJavaMessage = "Pour lancer Minecraft, vous avez besoin d'une installation 64-bit de Java {major}. Voulez-vous que nous en installions une ?"
installJava = "Installer Java"
installJavaManually = "Installer manuellement"
javaDownloadPrepare = "Préparation du téléchargement de Java..."
javaDownloadFailureTitle = "Erreur lors du téléchargement de Java"
javaDownloadFailureText = "Consultez la console (CTRL + Shift + i) pour plus de détails."
javaRequired = "Java est requis<br>pour lancer le jeu"
javaRequiredMessage = 'A valid x64 installation of Java {major} is required to launch.<br><br>Please refer to our <a href="https://github.com/dscalzi/HeliosLauncher/wiki/Java-Management#manually-installing-a-valid-version-of-java">Java Management Guide</a> for instructions on how to manually install Java.'
javaRequiredDismiss = "Je comprends"
javaRequiredCancel = "Retour"

[js.landing.downloadJava]
findJdkFailure = "Échec de la recherche d'une distribution OpenJDK."
javaDownloadCorruptedError = "Le JDK téléchargé a une signature incorrecte, le fichier est peut-être corrompu."
extractingJava = "Extraction de Java"
javaInstalled = "Java installé !"

[js.landing.dlAsync]
loadingServerInfo = "Chargement des informations du serveur..."
fatalError = "Erreur Fatale"
unableToLoadDistributionIndex = "Impossible de charger l'index de distribution. Consultez la console (CTRL + Shift + i) pour plus de détails."
pleaseWait = "Veuillez patienter..."
errorDuringLaunchTitle = "Erreur lors du lancement"
seeConsoleForDetails = "Consultez la console (CTRL + Shift + i) pour plus de détails."
validatingFileIntegrity = "Validation de l'intégrité des fichiers..."
errorDuringFileVerificationTitle = "Erreur lors de la vérification des fichiers"
downloadingFiles = "Téléchargement des fichiers..."
errorDuringFileDownloadTitle = "Erreur lors du téléchargement des fichiers"
preparingToLaunch = "Préparation du lancement..."
launchingGame = "Lancement du jeu..."
launchWrapperNotDownloaded = "Le fichier principal, LaunchWrapper, n'a pas pu être téléchargé. Le jeu ne peut pas démarrer.<br><br>Pour corriger cela, désactivez temporairement votre antivirus et relancez le jeu.<br><br>Si vous avez le temps, merci de <a href=\"https://github.com/dscalzi/HorizonLauncher/issues\">signaler le problème</a> en précisant votre antivirus."
doneEnjoyServer = "Terminé. Bon jeu !"
checkConsoleForDetails = "Veuillez consulter la console (CTRL + Shift + i) pour plus de détails."

[js.landing.news]
checking = "Vérification des nouvelles"

[js.landing.discord]
loading = "Chargement du jeu..."
joining = "Navigation vers la République d'Horizon !"
joined = "Explore l'Horizon !"

[js.overlay]
dismiss = "Fermer"

[js.settings.fileSelectors]
executables = "Exécutables"
allFiles = "Tous les fichiers"

[js.settings.mstfLogin]
errorTitle = "Un problème est survenu"
errorMessage = "L'authentification Microsoft a échoué. Veuillez réessayer."
okButton = "OK"

[js.settings.mstfLogout]
errorTitle = "Un problème est survenu"
errorMessage = "La déconnexion Microsoft a échoué. Veuillez réessayer."
okButton = "OK"

[js.settings.authAccountSelect]
selectButton = "Sélectionner le compte"
selectedButton = "Compte sélectionné &#10004;"

[js.settings.authAccountLogout]
lastAccountWarningTitle = "Attention<br>C'est votre dernier compte"
lastAccountWarningMessage = "Pour utiliser le launcher, vous devez être connecté à au moins un compte. Vous devrez vous reconnecter après.<br><br>Êtes-vous sûr de vouloir vous déconnecter ?"
confirmButton = "Je suis sûr"
cancelButton = "Annuler"

[js.settings.authAccountPopulate]
username = "Nom d'utilisateur"
uuid = "UUID"
selectAccount = "Sélectionner le compte"
selectedAccount = "Compte sélectionné ✓"
logout = "Déconnexion"

[js.settings.dropinMods]
removeButton = "Supprimer"
deleteFailedTitle = "Échec de la suppression<br>du mod {fullName}"
deleteFailedMessage = "Vérifiez que le fichier n'est pas utilisé et réessayez."
failedToggleTitle = "Échec de l'activation<br>d'un ou plusieurs mods"
okButton = "OK"

[js.settings.serverListing]
mainServer = "Serveur Principal"

[js.settings.java]
selectedJava = "Sélectionné : Java {version} ({vendor})"
invalidSelection = "Sélection invalide"
requiresJava = "Requiert Java {major} x64."
availableOptions = "Options disponibles pour Java {major} (HotSpot VM)"

[js.settings.about]
preReleaseTitle = "Pre-release"
stableReleaseTitle = "Version Stable"
releaseNotesFailed = "Échec du chargement des notes de version."

[js.settings.updates]
newReleaseTitle = "Nouvelle version disponible"
newPreReleaseTitle = "Nouvelle Pre-release disponible"
downloadingButton = "Téléchargement..."
downloadButton = 'Télécharger sur GitHub<span style="font-size: 10px;color: gray;text-shadow: none !important;">Fermez le launcher et lancez le dmg pour mettre à jour.</span>'
latestVersionTitle = "Vous utilisez la dernière version"
checkForUpdatesButton = "Vérifier les mises à jour"
checkingForUpdatesButton = "Vérification..."

[js.settings.msftLogin]
errorTitle = "Échec de la connexion Microsoft"
errorMessage = "Nous n'avons pas pu authentifier votre compte Microsoft. Veuillez réessayer."
okButton = "OK"

[js.uibinder.startup]
fatalErrorTitle = "Erreur Fatale : Impossible de charger l'index de distribution"
fatalErrorMessage = "Aucune connexion n'a pu être établie avec nos serveurs pour télécharger l'index de distribution. L'index de distribution est un fichier essentiel qui fournit les dernières informations du serveur. Le launcher ne peut pas démarrer sans lui. Vérifiez votre connexion internet et relancez l'application."
closeButton = "Fermer"

[js.uibinder.validateAccount]
failedMessageTitle = "Échec de l'actualisation de la connexion"
failedMessage = "Nous n'avons pas pu actualiser la connexion pour <strong>{account}</strong>. Veuillez sélectionner un autre compte ou vous reconnecter."
failedMessageSelectAnotherAccount = "Nous n'avons pas pu actualiser la connexion pour <strong>{account}</strong>. Veuillez vous reconnecter."
loginButton = "Connexion"
selectAnotherAccountButton = "Choisir un autre compte"

[js.uicore.autoUpdate]
checkingForUpdateButton = "Vérification des mises à jour..."
installNowButton = "Installer maintenant"
checkForUpdatesButton = "Vérifier les mises à jour"

[js.auth.microsoft.error]
noProfileTitle = "Erreur de connexion :<br>Profil non configuré"
noProfileDesc = "Votre compte Microsoft n'a pas encore de profil Minecraft. Si vous venez d'acheter le jeu ou de l'obtenir via le Game Pass, vous devez créer votre profil sur <a href=\"https://minecraft.net/\">Minecraft.net</a>."
noXboxAccountTitle = "Erreur de connexion :<br>Pas de compte Xbox"
noXboxAccountDesc = "Votre compte Microsoft n'a aucun compte Xbox associé."
xblBannedTitle = "Erreur de connexion :<br>Xbox Live indisponible"
xblBannedDesc = "Votre compte Microsoft provient d'un pays où le Xbox Live est indisponible ou banni."
under18Title = "Erreur de connexion :<br>Approbation parentale requise"
under18Desc = "Les comptes pour utilisateurs de moins de 18 ans doivent être ajoutés à une Famille par un adulte."
unknownTitle = "Erreur inconnue lors de la connexion"
unknownDesc = "Une erreur inconnue est survenue. Veuillez consulter la console pour plus de détails."

[js.auth.mojang.error]
methodNotAllowedTitle = "Erreur interne :<br>Méthode non autorisée"
methodNotAllowedDesc = "Méthode non autorisée. Veuillez signaler cette erreur."
notFoundTitle = "Erreur interne :<br>Non trouvé"
notFoundDesc = "Le point de terminaison d'authentification est introuvable."
accountMigratedTitle = "Erreur de connexion :<br>Compte migré"
accountMigratedDesc = "Vous tentez de vous connecter avec un compte migré. Utilisez l'e-mail du compte comme identifiant."
invalidCredentialsTitle = "Erreur de connexion :<br>Identifiants invalides"
invalidCredentialsDesc = "L'e-mail ou le mot de passe est incorrect. Veuillez réessayer."
tooManyAttemptsTitle = "Erreur de connexion :<br>Trop de tentatives"
tooManyAttemptsDesc = "Trop de tentatives de connexion sur ce compte. Veuillez réessayer plus tard."
invalidTokenTitle = "Erreur de connexion :<br>Jeton invalide"
invalidTokenDesc = "Le jeton d'accès fourni est invalide."
tokenHasProfileTitle = "Erreur de connexion :<br>Jeton déjà utilisé"
tokenHasProfileDesc = "Le jeton d'accès a déjà un profil assigné."
credentialsMissingTitle = "Erreur de connexion :<br>Identifiants manquants"
credentialsMissingDesc = "L'identifiant/mot de passe n'a pas été soumis ou le mot de passe fait moins de 3 caractères."
invalidSaltVersionTitle = "Erreur de connexion :<br>Version de Salt invalide"
invalidSaltVersionDesc = "Version de salt invalide."
unsupportedMediaTypeTitle = "Erreur interne :<br>Type de média non supporté"
unsupportedMediaTypeDesc = "Type de média non supporté. Veuillez signaler cette erreur."
accountGoneTitle = "Erreur de connexion :<br>Compte migré"
accountGoneDesc = "Ce compte a été migré vers un compte Microsoft. Veuillez vous connecter avec Microsoft."
unreachableTitle = "Erreur de connexion :<br>Inaccessible"
unreachableDesc = "Impossible de joindre les serveurs d'authentification. Vérifiez votre connexion."
gameNotPurchasedTitle = "Erreur de connexion :<br>Jeu non acheté"
gameNotPurchasedDesc = "Ce compte ne possède pas Minecraft. Vous pouvez l'acheter sur <a href=\"https://minecraft.net/\">Minecraft.net</a>"
unknownErrorTitle = "Erreur inconnue lors de la connexion"
unknownErrorDesc = "Une erreur inconnue est survenue. Veuillez consulter la console pour plus de détails."